import sys

'''
given an oov file generated by moses, generate a list of unique oov words
'''

oov_file = sys.argv[1]
oov_file_unique = sys.argv[2]

vocab = set()

# read Moses-output oov file
ctr = 0
with open(oov_file) as f:
    for line in f:
        words = line.strip().split(' ')
        for word in words:
            vocab.add(word)
        ctr += 1
print(str(ctr)+" lines processed.")

# write unique oov file
ctr = 0
with open(oov_file_unique, 'w') as fw:
    for word in vocab:
        fw.write(word)
        fw.write('\n')
        ctr += 1
print(str(ctr)+" words written to file.")
